/**
 * Turns the render archive in public/work/ into web-ready WebP in public/media/
 * and writes lib/media.generated.ts alongside it.
 *
 * Why this exists: the source renders are 200MB of full-resolution PNG/JPEG.
 * They cannot be served, and next/image refuses to lay out a remote-shaped
 * image without knowing its intrinsic size — so the same pass that compresses
 * also records dimensions, which is what stops mixed-orientation renders from
 * being cropped to a guessed aspect ratio.
 *
 *   node scripts/prepare-media.mjs
 *
 * Safe to re-run: unchanged files are skipped, so adding one render does not
 * reprocess the archive. Pass --force to rebuild everything.
 */

import { mkdir, readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC = path.join(ROOT, "public", "work");
const OUT = path.join(ROOT, "public", "media");
const MANIFEST = path.join(ROOT, "lib", "media.generated.ts");

/** Widest we ever need: a full-bleed plate on a 2x display, and no wider. */
const MAX_WIDTH = 2400;
const QUALITY = 82;
const FORCE = process.argv.includes("--force");

/** Screen grabs, screen recordings and scratch files stay out of the build. */
const EXCLUDE = [
  /^Screenshot/i,
  /\.mov$/i,
  /^dinosaur\./i,
  /^yummers\./i,
  /^rednblue\./i,
  /^rb_topdown\./i,
];

const isImage = (file) => /\.(png|jpe?g|webp)$/i.test(file);
const excluded = (file) => EXCLUDE.some((pattern) => pattern.test(file));

async function newerThan(source, target) {
  try {
    const [a, b] = await Promise.all([stat(source), stat(target)]);
    return a.mtimeMs > b.mtimeMs;
  } catch {
    return true; // target missing
  }
}

const entries = [];
let processed = 0;
let skipped = 0;
let sourceBytes = 0;
let outputBytes = 0;

const slugs = (await readdir(SRC, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name);

for (const slug of slugs) {
  const sourceDir = path.join(SRC, slug);
  const outDir = path.join(OUT, slug);
  await mkdir(outDir, { recursive: true });

  const files = (await readdir(sourceDir)).filter(
    (file) => isImage(file) && !excluded(file),
  );

  for (const file of files) {
    const source = path.join(sourceDir, file);
    const base = file.replace(/\.[^.]+$/, "");
    const target = path.join(outDir, `${base}.webp`);

    sourceBytes += (await stat(source)).size;

    if (FORCE || (await newerThan(source, target))) {
      await sharp(source)
        .rotate() // honour EXIF before we read dimensions off the result
        .resize({ width: MAX_WIDTH, withoutEnlargement: true })
        .webp({ quality: QUALITY })
        .toFile(target);
      processed += 1;
    } else {
      skipped += 1;
    }

    const { width, height } = await sharp(target).metadata();
    outputBytes += (await stat(target)).size;

    entries.push({ key: `${slug}/${file}`, src: `/media/${slug}/${base}.webp`, width, height });
  }
}

entries.sort((a, b) => a.key.localeCompare(b.key));

const body = entries
  .map((e) => `  ${JSON.stringify(e.key)}: { src: ${JSON.stringify(e.src)}, width: ${e.width}, height: ${e.height} },`)
  .join("\n");

await writeFile(
  MANIFEST,
  `// GENERATED by scripts/prepare-media.mjs — do not edit by hand.
// Keys are "<slug>/<original filename>" so content files can keep referring to
// the source renders while the served asset stays an optimised WebP.

export type MediaAsset = { src: string; width: number; height: number };

export const media: Record<string, MediaAsset> = {
${body}
};
`,
  "utf8",
);

const mb = (bytes) => `${(bytes / 1024 / 1024).toFixed(1)}MB`;
console.log(
  `media: ${processed} converted, ${skipped} unchanged, ${entries.length} total\n` +
    `weight: ${mb(sourceBytes)} source -> ${mb(outputBytes)} served`,
);
